version: '2'
services:
    seed:
        build: 
            context: .
            dockerfile: Dockerfile-seed
        volumes:
            - /seed
    db:
        image: mongo
        volumes_from: 
            - seed
        command: ["/seed/seed.sh"]
    descriptions:
        build: ./descriptions
        links: 
            - db
        ports:
            - "3000:3000"
    ngbuild:
        build: ./usdaweb 
    web:
        build: 
            context: . 
            dockerfile: Dockerfile-web
        volumes_from:
            - ngbuild 
        ports:
            - "80:80"
        depends_on:
            - ngbuild
            - descriptions