FROM nginx 

MAINTAINER Jeremy Likness <jeremy@jeremylikness.com>

# take output from an Angular 2 CLI build and move it into
# a static nginx server 

RUN cp -a /src/dist/ /src/dist /usr/share/nginx/html/ \
    && rm -rf /src/dist
EXPOSE 80/tcp