version: '2'
services:
    seed:
        build: 
            context: .
            dockerfile: Dockerfile-seed
    db:
        image: mongo
        volumes_from: 
            - seed
        command: ["/seed/seed.sh"]
    descriptions:
        build: ./descriptions
        links: 
            - db
        ports:
            - "3000:3000"
    nutrients:
        build: ./nutrients
        links:
            - db
        ports:
            - "3001:3000"
    ngbuild:
        build: ./usdaweb 
        volumes:
            - ng2:/src/dist
    web:
        image: nginx 
        volumes:
            - ng2:/usr/share/nginx/html
        ports:
            - "80:80"
        depends_on:
            - descriptions
volumes:
    ng2: {}